import type { Config } from "tailwindcss";

// Design tokens ported from stitch_ghost_coach_form_analysis/DESIGN.md
// ("Ghost Coach" - Sand Dune / Hunter Green premium tactical palette).
const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        surface: "#fff9e9",
        "surface-dim": "#e1dabd",
        "surface-bright": "#fff9e9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fbf4d6",
        "surface-container": "#f6eed0",
        "surface-container-high": "#f0e8cb",
        "surface-container-highest": "#eae3c5",
        "on-surface": "#1f1c0a",
        "on-surface-variant": "#424842",
        "inverse-surface": "#34311d",
        "inverse-on-surface": "#f8f1d3",
        outline: "#727971",
        "outline-variant": "#c2c8bf",
        "surface-tint": "#45664a",
        primary: "#27472e",
        "on-primary": "#ffffff",
        "primary-container": "#3e5f44",
        "on-primary-container": "#b2d7b5",
        "inverse-primary": "#abd0ae",
        secondary: "#605f53",
        "on-secondary": "#ffffff",
        "secondary-container": "#e6e3d4",
        "on-secondary-container": "#666559",
        tertiary: "#174a26",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#30623c",
        "on-tertiary-container": "#a5dbab",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#c6ecc9",
        "primary-fixed-dim": "#abd0ae",
        "on-primary-fixed": "#01210c",
        "on-primary-fixed-variant": "#2d4e34",
        "secondary-fixed": "#e6e3d4",
        "secondary-fixed-dim": "#cac7b8",
        "on-secondary-fixed": "#1d1c13",
        "on-secondary-fixed-variant": "#48473c",
        "tertiary-fixed": "#b8f0bf",
        "tertiary-fixed-dim": "#9dd3a4",
        "on-tertiary-fixed": "#00210b",
        "on-tertiary-fixed-variant": "#1e502c",
        background: "#fff9e9",
        "on-background": "#1f1c0a",
        "surface-variant": "#eae3c5",
      },
      fontFamily: {
        sans: ["var(--font-plus-jakarta-sans)", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        "container-margin": "24px",
        gutter: "16px",
      },
      boxShadow: {
        soft: "0 10px 30px -5px rgba(62, 95, 68, 0.12)",
      },
    },
  },
  plugins: [],
};

export default config;
